### PR TITLE
Fix infinite recursion when @bind is used in IE11

### LINKED ISSUE #8: @bind() decorator not working in IE11
I have this small example:

```javascript
import { Component, h, define } from 'skatejs';

import { bind } from 'decko';

export default class App extends Component<void> {
  static get is() { return 'my-app'; }

  @bind()
  handleClick() {
    console.log( 'clicked with this scope: ', this );
  }

  renderCallback() {
    return [
      <div onClick={this.handleClick}>Hello my lord!</div>,
    ];
  }
};

define(App);
```

When I try this in IE (11) I have this error: 
image

In chrome it works properly... 

You can try it in this repository which I created for this issue:
https://github.com/davidrus/skate-starter

### PR DESCRIPTION
**Pull request by cronon**
this fixes https://github.com/developit/decko/issues/8

### CODE REVIEW

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
Awesome, thanks @cronon.

**Comment by cronon** [comment]
@developit no problem :)
when are you going to release new version of decko?

**Comment by TomaszBorczyk** [comment]
Hey, any idea when will 1.2.1 be released?

**Comment by TomaszBorczyk** [comment]
@developit 
Are there any plans for releasing a new version? It's been a few months since the fix was merged and the version was increased.

**Pull request merged**
