### PR TITLE
feat(ts-typings): add typescript definitions

### LINKED ISSUE #5: TS definitions
hey Jason. Would you be open to add TS definitions  for this project? If yes I'll sent PR.

thanks man!

### PR DESCRIPTION
**Pull request by Hotell**
Closes #5

### CODE REVIEW

**Comment by developit** [comment]
Awesome! Suggestions for someone to review?

**Comment by Hotell** [comment]
Hmm maybe our friend from #skatejs group https://github.com/vvakame

**Comment by Hotell** [comment]
or one of preact ts-definitions contributor https://github.com/developit/preact/blob/master/src/preact.d.ts

**Comment by developit** [comment]
@vvakame / @robertknight / @kruczy <3

**Comment by kruczy** [comment]
Looks good to me,
the tsformat dev dependency seems like a bit of an overkill but it does not really hurt so ¯\_(ツ)_/¯

**Comment by Hotell** [comment]
@kruczy 
> the tsformat dev dependency seems like a bit of an overkill but it does not really hurt so ¯_(ツ)_/¯

haha yeah, that's why we have devDeps right ? :P 🍺

**Pull request merged**
